name: Dispatch test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch name'
        required: true
        type: string

jobs:
  dispatch-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: git add
        run: |
          echo "${{ inputs.name }}" > test.txt
          git add test.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          title: "PR test"
          commit-message: "PR test"
          body: |
            PR test
          branch: ${{ inputs.name }}
