name: Inspect Windows environment

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check something
      shell: cmd
      run: |
        cd
        set
        dir c:\
        dir "c:\Program Files"
        dir "c:\Program Files (x86)\Microsoft Visual Studio"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
        dir c:\hostedtoolcache
        dir c:\hostedtoolcache\windows
        dir c:\hostedtoolcache\windows\Python
        dir c:\hostedtoolcache\windows\Python\3.8.0
        dir c:\hostedtoolcache\windows\Python\3.8.0\x64
        dir c:\hostedtoolcache\windows\Python\3.8.0\x86
        dir c:\hostedtoolcache\windows\Ruby
        dir c:\hostedtoolcache\windows\Ruby\2.6.3
        dir c:\hostedtoolcache\windows\Ruby\2.6.3\x64
        where git
        where hg
        git version
        hg version
        C:\Strawberry\perl\bin\perl.exe -v
        call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall"
        cl
