name: Inspect Windows environment

on: [push]

env:
  RUBY_BRANCH: ruby_2_6
  #RUBY_SRC_URL: https://github.com/ruby/ruby/archive/${{ env.RUBY_BRANCH }}.zip

jobs:
  build:

    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v2
    - name: Check something
      shell: cmd
      env:
        RUBY_SRC_URL: https://github.com/ruby/ruby/archive/${{ env.RUBY_BRANCH }}.zip
      run: |
        cd
        set
        dir c:\
        dir c:\msys64\mingw64\bin
        dir "c:\Program Files"
        dir "c:\Program Files (x86)"
        dir "c:\Program Files (x86)\Microsoft Visual Studio"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
        dir "%ProgramFiles(x86)%\Microsoft SDKs\Windows"
        dir c:\hostedtoolcache
        dir c:\hostedtoolcache\windows
        dir c:\hostedtoolcache\windows\Python
        dir c:\hostedtoolcache\windows\Python\3.8.1
        dir c:\hostedtoolcache\windows\Python\3.8.1\x64
        dir c:\hostedtoolcache\windows\Python\3.8.1\x86
        dir c:\hostedtoolcache\windows\Ruby
        dir c:\hostedtoolcache\windows\Ruby\2.6.5
        dir c:\hostedtoolcache\windows\Ruby\2.6.5\x64
        dir c:\hostedtoolcache\windows\Ruby\2.7.0
        where git
        where hg
        where curl
        git version
        hg version
        C:\Strawberry\perl\bin\perl.exe -v
        c:\hostedtoolcache\windows\Ruby\2.6.3\x64\bin\ruby -v
        call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall"
        cl
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        git config -l
    - name: Run VC2019
      shell: cmd
      run: |
        cl
        call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall" x86
        cl
    - name: Read Python path from registry
      shell: cmd
      run: |
        reg query HKLM\SOFTWARE\Python\PythonCore\3.8\InstallPath /reg:64 /ve
        reg query HKLM\SOFTWARE\Python\PythonCore\3.8-32\InstallPath /reg:32 /ve
    - name: Test escape sequence
      env:
        ESC: "\x1b"
      shell: cmd
      run: |
        echo %ESC%[31mRed%ESC%[m
#    - name: Test push
#      shell: cmd
#      run: |
#        git config --local user.name "vim-kt CI"
#        git config --local user.email "k-takata@users.noreply.github.com"
#        git commit --allow-empty -m "Test commit"
#        git push
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"
