name: Inspect Windows environment

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check something
      shell: cmd
      run: |
        cd
        set
        dir c:\
        dir "c:\Program Files"
        dir "c:\Program Files (x86)\Microsoft Visual Studio"
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2019"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0"
        dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
        dir c:\hostedtoolcache
        dir c:\hostedtoolcache\windows
        where git
        where hg
