name: Matrix test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x64, x86]

    env:
      ARCH: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v1
    - name: test script
      run: |
        echo $ARCH
        # Check API rate limit
        curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit
        curl -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
